name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: dropdown
    id: target
    attributes:
      label: Target
      options:
        - JVM
        - JS/Node
        - Native (Linux)
        - Native (macOS)
        - Native (iOS)
        - CLI (Rust)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.1.0"
    validations:
      required: true
