name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature or improvement
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      placeholder: What problem does this solve? What's your use case?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Have you tried any workarounds?
    validations:
      required: false
